app = "platform-phx"
primary_region = "ewr"

[build]
  dockerfile = "Dockerfile"

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "platform-phx.fly.dev"
  PHX_SERVER = "true"
  PORT = "4000"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[metrics]
  port = 9568
  path = "/metrics"

[[vm]]
  cpu_kind = "performance"
  cpus = 2
  memory_mb = 4096
